import type { Dict } from "./types";

const R300 = "R$300M";

// English copy. Anything [in brackets] is still to be filled in.
export const en: Dict = {
  lang: "en",
  meta: {
    title: "Fábio Pereira · Business, software and AI",
    description: "I turn messy problems into software that works. Co-founder of Espaces, a social recommendation app with AI, and builder of an ERP made with AI.",
  },
  nav: { projects: "Projects", journey: "Journey", contact: "Contact", cases: "Cases", other: "PT", otherHref: "/", home: "/en", portfolio: "Portfolio · 2026" },
  ids: { espaces: "espaces", erp: "erp", others: "other-projects", journey: "journey", how: "how-i-work", contact: "contact" },
  hero: {
    kicker: "BUSINESS × SOFTWARE × AI",
    statement: "I turn messy problems into software that works.",
    sub: "I started by automating finance with Python and SQL. Today I build products with data and AI, from the first sketch to the operation running.",
    figCaption: "São Paulo, 2026",
    start: "See the projects",
    stats: [
      { label: "PRODUCT", title: "Co-founder of Espaces", value: "1M+", caption: "product visitors", href: "#espaces" },
      { label: "SYSTEMS", title: "ERP built with AI", value: R300, caption: "a year in operations", href: "#erp" },
      { label: "DATA", title: "Customer data platform", value: "2.4M", caption: "unified people", href: "#other-projects" },
    ],
    originLabel: "ORIGIN", originTitle: "Production Engineering",
  },
  projectLabel: "PROJECT",
  espaces: {
    id: "espaces", n: "01",
    kicker: "2023 — TODAY · CO-FOUNDER",
    name: "Espaces",
    tagline: "Where to eat and drink, based on what your friends thought.",
    body: "A social recommendation app with **over 1 million visitors** and **20K registered users**. You review the places you went, see where your friends actually eat and ask Rango, an AI assistant, the way you'd say it out loud. It started as an internal project in 2023 and became a company in 2024.",
    roleLabel: "MY ROLE",
    role: "Co-founder. Product, engineering, data and infrastructure, from the first sketch to the app in the stores.",
    stats: [],
    tags: ["React Native", "NestJS", "PostgreSQL · pgvector", "LLMs", "AWS · Kubernetes"],
    cta: { label: "Read the Espaces case study", href: "/en/cases/espaces" },
    figCaption: "Fig. 2 · Friends feed, Rango and venue page",
    figNote: "fictional places and people",
    screens: { feed: "Friends feed", rango: "Rango, the AI assistant", avaliar: "Review in four reactions", lugar: "Venue page" },
  },
  erp: {
    id: "erp", n: "02",
    kicker: "2026 · BUILT WITH AI",
    name: "An ERP from scratch",
    tagline: "A live music company's entire operation in a single system.",
    body: `Sales, operations, legal, tax, finance and reporting, plus an app for the crew on the road. It runs a **${R300}-a-year operation** and **more than 100 people** use it every day. I built it in 7 months, with AI in how I build.`,
    roleLabel: "MY ROLE",
    role: "End to end: discovery, architecture, build and rollout.",
    stats: [],
    tags: ["Next.js", "Fastify", "Prisma", "PostgreSQL", "Expo", "AWS · EKS"],
    cta: { label: "Read the ERP case study", href: "/en/cases/erp" },
    figCaption: "Fig. 3 · Monthly schedule and the crew app",
    figNote: "sample data",
    before: "BEFORE",
    notes: ["the deal lived in a chat", "contacts stayed with the seller", "schedule_v7_FINAL2.xlsx", "history leaving with people"],
    windowTitle: "events · september 2026",
    screens: { month: "Monthly schedule with 67 shows by status", app: "Crew app with the day's schedule" },
  },
  others: {
    kicker: "OTHER PROJECTS",
    title: "Along the way.",
    items: [
      {
        kicker: "2025 · DATA", title: "Customer data platform", figure: "data",
        body: "A bar group's customers were scattered across a cashless POS. I unified **17 million events** into one profile per CPF, with **2.4 million people**, segments, campaigns and an AI that answers questions about the data.",
        stats: [], tags: ["ClickHouse", "TypeScript", "Next.js", "Supabase", "OpenAI"],
        link: { label: "Read the case study", href: "/en/cases/dados" },
      },
      {
        kicker: "2024 · FINANCE · DETERMINISTIC FIRST", title: "Invoice check", figure: "invoice",
        body: "**More than 3,000 invoices a month** were checked by hand. Now the check is automated and **deterministic first**: rules handle most of it, and OCR, vision models and AI only step in when they fail. Lower cost, lower latency.",
        stats: [], tags: ["Python", "Tesseract", "Vision models", "Queue", "AWS serverless", "MySQL"],
        link: { label: "Read the case study", href: "/en/cases/notas" },
      },
    ],
    social: {
      kicker: "ESPACES · CONTENT",
      title: "From zero to almost 20K on Instagram, in 1 year.",
      body: "In 1 year, I took Espaces' Instagram from zero to **almost 20K followers**. I went to the places, narrated, filmed, edited and posted. One of the videos passed **1.9 million views**.",
      steps: ["go to the place", "narrate", "film", "edit", "post"],
      reels: [
        { label: "The viral video · 1.9 million views", views: "1.9M+ views", photo: "/insta/viral-insights.jpg", ratio: "739 / 1200", hint: "" },
        { label: "The profile · 19.8K followers", photo: "/insta/perfil.jpg", hint: "" },
      ],
    },
  },
  journey: {
    kicker: "JOURNEY", title: "From spreadsheet to product.",
    lanes: { edu: "education", plat: "the platform", esp: "espaces" },
    graph: [
      { year: "2019", lane: "edu", tag: "Python" },
      { year: "2020", lane: "edu", tag: "CPA-20" },
      { year: "2021", lane: "plat", tag: "finance" },
      { year: "2022", lane: "plat", tag: "automation" },
      { year: "2023", lane: "edu", tag: "graduation" },
      { year: "2023", lane: "plat", tag: "R$4M/month" },
      { year: "2024", lane: "plat", tag: "PM" },
      { year: "2024", lane: "esp", tag: "co-founder" },
      { year: "2025", lane: "plat", tag: "product" },
      { year: "2025", lane: "esp", tag: "data & AI" },
      { year: "2026", lane: "plat", tag: "ERP" },
      { year: "2026", lane: "esp", tag: "infra" },
    ],
    items: [
      {
        year: "2019", title: "Production Engineering", text: "At Mauá, a year of algorithms in Python opened my eyes to programming.",
        detail: {
          body: "I started Production Engineering at Mauá. The first-year intro to algorithms was a full year of **Python**, and that's what opened my eyes to programming. The same year, I was on the team that founded the financial markets league, where I was academic director and taught financial products.",
          points: ["A year of algorithms in Python: the foundation for everything after", "Founding team of the financial markets league", "Academic director of the league, teaching financial products"],
          tags: ["Python", "Algorithms", "Finance"],
        },
      },
      {
        year: "2020", title: "Financial markets", text: "Python in depth, a first contact with SQL and a lot of financial markets.",
        detail: {
          body: "A year preparing to work in financial markets: **Python** in more depth, an intro to **SQL** in Information Systems classes and a lot of market study.",
          points: ["4 online courses in quantitative modeling, risk and decisions (Wharton)", "Operando como Institucional (Quantzed)", "CPA-20 certification (ANBIMA)", "Desafio Quantamental and Challenge IGC – M&A"],
          tags: ["Python", "SQL", "Quantitative finance"],
        },
      },
      {
        year: "2021", title: "Finance, operations and innovation", text: "Joined the largest live music booking platform and took on innovation too.",
        detail: {
          body: "At the end of 2020, I joined **the largest live music booking platform** to run finance and operations. I quickly stood out by building the area's controls, and took on **innovation** as well.",
          points: ["Built the finance and operations controls, first in spreadsheets", "Took on the innovation area"],
          tags: ["Finance", "Operations", "Innovation"],
        },
      },
      {
        year: "2022", title: "Finance transformation", text: "We moved from manual processes to automating much of finance.",
        detail: {
          body: "The year finance stopped depending on manual processes. I automated much of the work with **Python and SQL**, reduced the team's dependence on so many people and relieved the operation's **bottlenecks**.",
          points: ["Closings that took **days** started taking **hours**", "Manual steps replaced with Python and SQL scripts", "Less dependence on people and bottlenecks relieved"],
          stat: ["5→1", "people in the operation"],
          tags: ["Python", "SQL", "Automation"],
        },
      },
      {
        year: "2023", title: "Running the finance operation", text: "Took over the platform's finance operation, graduated and joined Agenda Cultural.",
        detail: {
          body: "I took over the platform's finance operation: **100% of accounts payable and receivable** and control over **more than R$4 million transacted every month**. The same year, I graduated. At the end of the year, I got involved with **Agenda Cultural**, a portal showing the live shows at more than 200 bars and restaurants across Brazil.",
          points: ["Owned 100% of accounts payable and accounts receivable", "Control over **more than R$4 million** transacted monthly on the platform", "Graduated in Production Engineering", "Agenda Cultural: shows from **more than 200 bars and restaurants** across Brazil in one portal"],
          stat: ["R$4M+", "transacted monthly under my control"],
          tags: ["Finance", "Operations", "Product"],
        },
      },
      {
        year: "2024", title: "Espaces and product", text: "Agenda Cultural becomes Espaces, and at the end of the year I take on product at the platform.",
        detail: {
          body: "Agenda Cultural became **Espaces** and I became a co-founder. The same year, I automated invoice checks, **deterministic first**. After the experience with Espaces, at the end of the year I also took over **product** at the platform, working as a product manager.",
          points: ["Co-founder of Espaces", "Automated check of **more than 3,000 invoices a month**", "At the end of the year, product manager at the platform"],
          stat: ["3,000+", "invoices a month checked automatically"],
          tags: ["Product", "Python", "AWS"],
          links: [{ label: "Espaces case study", href: "/en/cases/espaces" }, { label: "Invoice case study", href: "/en/cases/notas" }],
        },
      },
      {
        year: "2025", title: "Data, AI and product", text: "Hands-on data and AI projects at Espaces, and product close to the CEO at the platform.",
        detail: {
          body: "At Espaces, I started more hands-on **data and AI** projects, like the customer data platform, with **17 million events** unified into **2.4 million people**. At the platform, I kept running product: close to the CEO, defining the backlog, planning sprints and writing documentation.",
          points: ["Customer data platform with ClickHouse and AI to query and segment", "Product at the platform: backlog, sprints and documentation, close to the CEO"],
          stat: ["2.4M", "unified people"],
          tags: ["ClickHouse", "OpenAI", "Product"],
          links: [{ label: "Data case study", href: "/en/cases/dados" }],
        },
      },
      {
        year: "2026", title: "Back to code", text: "More hands-on: the ERP on my own and all of Espaces' infrastructure.",
        detail: {
          body: `I went back to coding more. At the platform, I'm still responsible for product and also pick up tasks myself. I took on the ERP project on my own, since the team had no availability: today it runs a **${R300}-a-year operation**. At Espaces, I stepped up and became the owner of **all the infrastructure**.`,
          points: ["ERP taken on alone: **523 commits** in 7 months", "Product and tasks at the platform", "Owner of all of Espaces' infrastructure"],
          stat: [R300, "a year running on the ERP"],
          tags: ["Next.js", "Fastify", "Prisma", "Kubernetes", "AWS"],
          links: [{ label: "ERP case study", href: "/en/cases/erp" }],
        },
      },
    ],
  },
  how: {
    kicker: "HOW I WORK",
    title: "Business × Software × AI.",
    body: "I'm not just AI, and not just software. What I do is bring both together with the business.",
    hint: "Hover or tap the regions",
    circles: { b: "BUSINESS", s: "SOFTWARE", a: "AI" },
    regions: [
      { key: "bsa", label: "BUSINESS × SOFTWARE × AI", text: "Where I work: understand the problem with the people living it, build the whole system and use AI where it actually helps. Until people are using it." },
      { key: "bs", label: "BUSINESS × SOFTWARE", text: "Systems that solve the problem but leave on the table what AI already does well." },
      { key: "ba", label: "BUSINESS × AI", text: "Good AI ideas that stay on the slide, because nobody builds them." },
      { key: "sa", label: "SOFTWARE × AI", text: "Cutting-edge technology looking for a problem to solve." },
      { key: "b", label: "BUSINESS ONLY", text: "Knows exactly what the problem is, but depends on someone else to build the solution." },
      { key: "s", label: "SOFTWARE ONLY", text: "Builds well, but not always what matters most to the business." },
      { key: "a", label: "AI ONLY", text: "Impressive demos that never reach anyone's day-to-day." },
    ],
  },
  figures: {
    illustrative: "illustrative",
    enrichLabel: "WHAT AI GENERATES FOR EACH VENUE", enrichItems: ["Curated photos", "Venue description", "Menu and booking links"],
    builtLabel: "WHAT I BUILT", builtItems: ["iOS and Android app", "Website and neighborhood pages", "Business dashboard", "APIs and AWS infrastructure"],
    stackLabel: "STACK", stack: ["React Native", "NestJS", "PostgreSQL", "pgvector", "Kubernetes", "AWS"],
  },
  foundations: {
    kicker: "FOUNDATIONS", title: "Where I come from.", verify: "verify ↗",
    degree: {
      years: "2019 — 2023",
      title: "Production Engineering",
      school: "Instituto Mauá de Tecnologia",
      items: [
        { title: "Financial Markets League", text: "Founding team · academic director, teaching financial products" },
      ],
    },
    certsLabel: "CERTIFICATIONS AND COURSES",
    certs: [
      { year: "2020", title: "4 online courses in quantitative modeling, risk and decisions", issuer: "Wharton · University of Pennsylvania" },
      { year: "2020", title: "Operando como Institucional", issuer: "Quantzed", note: "trading, options, portfolio and quantitative strategies · grade 10/10" },
      { year: "2020", title: "CPA-20", issuer: "ANBIMA", note: "obtained in my 2nd year of college" },
    ],
  },
  life: {
    kicker: "BEYOND WORK", title: "Off screen.", photoMissing: "photo coming soon",
    items: [
      { title: "Tennis", photo: "/life/tenis.jpg", photoPos: "50% 22%", photoHint: "[your tennis photo]", text: "I played competitive tennis and traveled to more than 15 states for Brazilian and South American championships." },
      { title: "Food", tag: "149+ reviews on Espaces", photo: "/life/perfil-espaces.jpg", photoPos: "50% 0%", light: true, photoHint: "[a frame from one of your videos]", text: "Eating out has always been my thing. So has telling friends where to go. Espaces brought that together with technology." },
      { title: "Poker", photo: "/life/poker-campeao.jpg", framed: true, photoHint: "", text: "I studied it a lot and took a few courses when I was younger. Today I play online tournaments for fun. I think a lot of my taste for numbers and probability comes from there." },
    ],
  },
  contact: {
    kicker: "CONTACT", title: "Got a messy problem?", text: "I'm open to new opportunities in applied AI, product and engineering. Tell me what you're trying to solve.",
    email: "fabio.gofferje@gmail.com", copy: "COPY", copied: "COPIED", cv: "Résumé coming soon", place: "São Paulo, Brazil",
  },
  footer: { made: "Made by hand, with code." },
  espacesCase: {
    crumb: "01 · Espaces",
    next: { label: "Next case · ERP", href: "/en/cases/erp" },
    back: "Back to the projects",
    kicker: "2023 — TODAY · CO-FOUNDER · PRODUCT, ENGINEERING, DATA AND INFRA",
    title: "Where to eat, based on what your friends thought.",
    lead: "Strangers' ratings don't help you pick a place for dinner. Espaces shows where the people you know actually eat and what they thought, and lets you ask an AI assistant in your own words. Over **1 million visitors** have come through, and **20K people** have signed up.",
    stats: [],
    galleryCaption: "Fig. 1 · The app, end to end",
    gallery: [["feed", "Friends feed"], ["rango", "Rango, the AI assistant"], ["avaliar", "Review in four reactions"], ["lugar", "Venue page"]],
    sections: [
      { title: "A social product", body: "The heart of the app is what your network does: each review has a photo, text and one of four reactions. The venue page sums up what your friends thought before the overall average." },
      { title: "Rango: AI inside the product", figure: "ai", body: "People ask in their own words, “good, cheap sushi near me”, and Rango understands the intent, not just the keywords. Search is semantic, and what friends thought weighs in the ranking." },
      { title: "Enrichment with AI", figure: "enrich", body: "Every venue gets curated photos, a description and menu and booking links, generated by an LLM pipeline that runs daily in batches, with a cost ceiling and link checks." },
      { title: "The platform", figure: "platform", body: "iOS and Android apps, website, business dashboard and APIs: NestJS services on Kubernetes on AWS, with PostgreSQL and pgvector. I design, build and run it." },
    ],
    decisionsLabel: "DECISIONS THAT MATTERED",
    decisions: [
      "Replace the 1-to-5 rating with four reactions: didn't like, ok, liked and favorite. Faster to give, easier to read.",
      "Recommend based on what your friends thought, not on strangers' averages.",
      "Enrich venues with AI in batches, with a cost ceiling per venue, instead of entering everything by hand.",
    ],
    lessonLabel: "WHAT I'D DO DIFFERENTLY", lesson: "[An honest lesson about Espaces]",
  },
  notasCase: {
    crumb: "03 · Invoices",
    next: { label: "Next case · Customer data", href: "/en/cases/dados" },
    back: "Back to the projects",
    kicker: "2024 · FINANCE · DETERMINISTIC FIRST",
    title: "3,000 invoices a month. AI only where needed.",
    lead: "Every month, more than **3,000 invoices** from artists were checked by hand. I built the system that does this check on its own, around one principle: **deterministic first**. Regex, lists and rules handle most of it; OCR, vision models and AI only step in when they fail. Using AI for everything would cost far more and slow down feedback to the artist.",
    stats: [],
    specLabel: "THE PROBLEM IN NUMBERS",
    spec: [["3,000+", "invoices a month"], ["5,000+", "city halls, each with its own template"], ["3", "reading paths: text, OCR and vision"], ["3", "fields checked against the database"]],
    sections: [
      { title: "Work that grew with the operation", body: "More shows meant more invoices. The check was the same, repeated thousands of times a month, and whoever did it had no time left for anything else.", items: ["Open each PDF", "Find CNPJ, amount and service code", "Compare with the database", "Tell the artist when something didn't match"] },
      { title: "Reading what isn't text", figure: "invoice", body: "In the common case, reading the PDF's text is enough. But some invoices arrived scanned, with no text at all. For those, OCR with Tesseract; when even OCR couldn't read with confidence, a vision model. Every invoice goes through the cheapest path that works." },
      { title: "Deterministic first, AI only where needed", body: "Each city hall has its own invoice template: the position and name of each field change from one city to another, and sometimes with the company's tax regime. Sending every invoice to an AI model would work, but at a huge cost and with more latency. So extraction tries the deterministic path first, and only what the rules can't solve goes to AI.", items: ["Regex to find the CNPJs", "A list of service codes to identify the code", "Label lists to find the amount field", "An AI model as fallback, only to classify what's left"] },
      { title: "Check what matters", body: "The invoice doesn't need to be understood in full. It needs to match three fields against what the database expects: CNPJ, amount and service code. When something is off, the artist knows exactly what to fix." },
      { title: "Fast and queued", body: "Artists needed quick feedback, and at month-end the volume arrives all at once. Invoices go into a queue and are processed by serverless functions on AWS, in Python, reading and writing to the company's MySQL database." },
    ],
    decisionsLabel: "DECISIONS THAT MATTERED",
    decisions: [
      "AI only where deterministic rules fail: in reading (text, then OCR, then a vision model) and in extraction (regex and lists, then AI). Cost and latency stay low.",
      "Check the three fields that decide the invoice, instead of trying to understand the whole document.",
      "Queue and serverless to absorb the month-end peak without idle servers the rest of the time.",
    ],
    lessonLabel: "WHAT I'D DO DIFFERENTLY", lesson: "[An honest lesson from the project]",
  },
  cdpCase: {
    crumb: "04 · Customer data",
    next: { label: "Next case · Espaces", href: "/en/cases/espaces" },
    back: "Back to the projects",
    kicker: "2025 · DATA · DETERMINISTIC + AI",
    title: "2.4 million people, one profile each.",
    lead: "Customer data for a group of bars and restaurants lived scattered across a cashless POS: check-ins on one side, payments on another, items sold on a third. I built the platform that brings it all into one profile per CPF, with **2.4 million people**, and lets marketing segment, ask the data questions with AI and send campaigns.",
    stats: [],
    specLabel: "THE SCALE OF THE DATA",
    spec: [["17M", "check-in, purchase and item events"], ["2.4M", "people, one per CPF"], ["10M", "person × product rows"], ["3.4M", "person × venue rows"], ["11", "venues, each seeing only its own data"]],
    sections: [
      { title: "One person, three records", figure: "identity", body: "The POS delivers the same visit in three pieces: the check-in that opens the tab, the buyer who pays and the items sold. CPF is the only consistent field, because the POS requires a CPF to open a tab. From there, rules merge field by field with source priority; a filled value is never overwritten by an empty one, and each field keeps where it came from and when it changed." },
      { title: "Cleaning what the API sends", body: "Half the work was finding the ways the API gets things wrong. Each one became a deterministic rule, tested against real events.", items: ["Times in UTC with a fake -03:00 offset", "The same UUID reused on different days", "An operating day from 3 am to 3 am, not midnight", "CPF with a trailing * and phones in scientific notation", "Names with digits, all caps and lost accents"] },
      { title: "ClickHouse for fast answers", body: "It started in Postgres, with metrics stored as JSON. As volume grew, analytics moved to ClickHouse: events partitioned by month, people with versions replaced on every load, and materialized views that precompute what the dashboard asks. The load runs hourly and can run again without duplicating anything.", items: ["Product queries about 120x faster than the JSON version", "Person × venue metrics matching raw events 100%", "Idempotent loads: every event has a source id"] },
      { title: "Asking the data with AI", figure: "analyst", body: "Marketing asks in Portuguese and the AI writes the SQL. Before it runs, a guardrail checks it: read-only, filtered to the venues the user can see, and no document data. To build segments by chat, the AI searches products and categories with tools instead of getting the whole catalog in the prompt." },
      { title: "From segment to campaign", body: "Segments are rules stored as JSON and evaluated in ClickHouse with parameterized SQL. They feed e-mail campaigns with click tracking and WhatsApp campaigns with Meta-approved templates. Sending moved off Vercel to the ETL worker when timeouts started killing sends halfway." },
    ],
    decisionsLabel: "DECISIONS THAT MATTERED",
    decisions: [
      "CPF as a single deterministic key: the POS requires a CPF to open a tab, so records can be merged without fuzzy matching.",
      "Idempotency from the first load: running again never duplicates, because every event has a source id and tables replace versions.",
      "Metrics per person × venue, not global: a customer's 35 visits across the group become 29 + 3 + 3, and each venue sees only its own.",
    ],
    lessonLabel: "WHAT I'D DO DIFFERENTLY",
    lesson: "[Draft, please review] I normalized names and phones after data was already flowing in. The new rule applies to future loads, but what was already stored stays dirty. Today I'd clean everything at ingestion from day one.",
  },
  erpCase: {
    crumb: "02 · ERP",
    next: { label: "Next case · Invoices", href: "/en/cases/notas" },
    back: "Back to the projects",
    kicker: "2026 · SYSTEMS · BUILT WITH AI",
    title: `An ERP for a ${R300}-a-year operation.`,
    lead: "At a live music company, deals lived in chats, contacts stayed with whoever sold and each person knew one piece of the operation. When someone left, the history left too. I built from scratch the system that now runs that operation, with **more than 100 people** using it every day.",
    stats: [],
    specLabel: "IN ENGINEERING NUMBERS",
    spec: [["7 months", "from first commit to running system"], ["523", "commits, 94% mine"], ["107K", "lines of TypeScript"], ["52 · 270", "tables · endpoints"]],
    screensCaption: "Fig. 1 · The system, module by module",
    screensNote: "presentation screens with sample data",
    screens: [["eventos-mes", "Operations · monthly schedule"], ["clientes", "Sales · relationship history"], ["contratos", "Legal · contract generated from the event"], ["receber", "Finance · receivables and payout"]],
    sections: [
      { title: "The operation lived in people", body: "Spreadsheets, chats and personal calendars work while the same people stay around. The goal wasn't to swap spreadsheets for screens: it was to turn contacts, deals and history into company assets.", items: ["Deals lived in a message thread", "Contacts stayed in the seller's WhatsApp", "Each person knew one piece of the operation", "When someone left, the context left too"] },
      { title: "Six modules, one flow", figure: "flow", body: "Sales, legal, tax, operations and finance are the same event changing hands. The contract is born from the event, the sales order from the contract and the payout from the payment rule. Nobody retypes anything." },
      { title: "Rules that don't depend on memory", body: "Governance lives in the code, not in people's habits.", items: ["Every write creates a change log; every status change creates history", "Status and approval are separate fields: records created by sellers start pending until QA approves", "10 access profiles, checked on every write route", "All input validated with Zod; unique CPF and CNPJ"] },
      { title: "Simulate before switching on", body: "A new rule would automatically cancel reservations without a contract 72 hours before the show. Before switching it on, I ran it against real production data: the first version would have dropped shows still in active negotiation. We adjusted the criteria with the operations team, and the rule only goes live after a simulation." },
      { title: "Built with AI", body: "I wrote 94% of 523 commits in 7 months, with AI as a pair programmer. The project rules live in a document the AI reads before any change. AI writes code and SQL; anything that touches the production database, I run myself." },
    ],
    stepsLabel: "FROM ROLLOUT TO ROUTINE",
    steps: [
      ["Discovery", "Understand how the operation worked: who sells, who operates, where it gets stuck and what lived in spreadsheets."],
      ["Customization", "Commission rules, contract templates, event types and team permissions designed for that operation."],
      ["Rollout", "Records, history and schedule migrated in stages, with the team trained on what they use, without stopping the business."],
      ["Operation", "Stay close until the first full month closes inside the system, and adjust what the routine revealed."],
    ],
    decisionsLabel: "DECISIONS THAT MATTERED",
    decisions: [
      "The event as the backbone: contract, sales order and receivable are born from it, instead of each team keeping its own records.",
      "Separate status from approval, so operations keep moving without skipping governance.",
      "The system controls money but never moves it: receivables, payment rules and closing, with no access to bank accounts.",
    ],
    lessonLabel: "WHAT I'D DO DIFFERENTLY",
    lesson: "[Draft, please review] Building fast with AI, I left type-checking and tests out of CI. A broken route went unnoticed for months. Today I'd put type-checks and tests in the pipeline on day one.",
  },
};
