import type { Dict } from "./types";

const NB = " "; // espaço que não quebra: "R$ 300 mi" fica numa linha só
const R300 = `R$${NB}300${NB}mi`;

// Textos em português. O que está [entre colchetes] ainda falta preencher.
export const pt: Dict = {
  lang: "pt",
  meta: {
    title: "Fábio Pereira · Negócio, software e IA",
    description: "Transformo problemas bagunçados em software que funciona. Cofundador da Espaces, um app de recomendação social com IA, e autor de um ERP construído com IA.",
  },
  nav: { projects: "Projetos", journey: "Trajetória", contact: "Contato", cases: "Cases", other: "EN", otherHref: "/en", home: "/", portfolio: "Portfólio · 2026" },
  ids: { espaces: "espaces", erp: "erp", others: "outros-projetos", journey: "trajetoria", how: "como-trabalho", contact: "contato" },
  hero: {
    kicker: "NEGÓCIO × SOFTWARE × IA",
    statement: "Transformo problemas bagunçados em software que funciona.",
    sub: "Comecei automatizando finanças com Python e SQL. Hoje construo produtos com dados e IA, do primeiro rascunho à operação rodando.",
    figCaption: "São Paulo, 2026",
    start: "Ver os projetos",
    stats: [
      { label: "PRODUTO", title: "Cofundador da Espaces", value: "1M+", caption: "visitantes no produto", href: "#espaces" },
      { label: "SISTEMAS", title: "ERP construído com IA", value: R300, caption: "por ano em operação", href: "#erp" },
      { label: "DADOS", title: "Plataforma de clientes", value: "2,4M", caption: "pessoas unificadas", href: "#outros-projetos" },
    ],
    originLabel: "ORIGEM", originTitle: "Engenharia de Produção",
  },
  projectLabel: "PROJETO",
  espaces: {
    id: "espaces", n: "01",
    kicker: "2023 — HOJE · COFUNDADOR",
    name: "Espaces",
    tagline: "Onde comer e beber, pelo que seus amigos acharam.",
    body: "Um app de recomendação social com **mais de 1 milhão de visitantes** e **20 mil usuários cadastrados**. Você avalia os lugares que foi, vê onde seus amigos comem de verdade e pede ao Rango, um assistente com IA, do jeito que você falaria. Nasceu como projeto interno em 2023 e virou empresa em 2024.",
    roleLabel: "MEU PAPEL",
    role: "Cofundador. Produto, engenharia, dados e infraestrutura, do primeiro rascunho ao app nas lojas.",
    stats: [],
    tags: ["React Native", "NestJS", "PostgreSQL · pgvector", "LLMs", "AWS · Kubernetes"],
    cta: { label: "Ler o case da Espaces", href: "/cases/espaces" },
    figCaption: "Fig. 2 · Feed dos amigos, Rango e página do lugar",
    figNote: "lugares e pessoas fictícios",
    screens: { feed: "Feed dos amigos", rango: "Rango, o assistente com IA", avaliar: "Avaliação em quatro reações", lugar: "Página do lugar" },
  },
  erp: {
    id: "erp", n: "02",
    kicker: "2026 · CONSTRUÍDO COM IA",
    name: "Um ERP do zero",
    tagline: "Toda a operação de uma produtora de shows num sistema só.",
    body: `Comercial, operacional, jurídico, fiscal, financeiro e relatórios, mais um app para a equipe na estrada. Roda numa operação de **${R300} por ano** e **mais de 100 pessoas** usam todos os dias. Construí em 7 meses, com IA no jeito de construir.`,
    roleLabel: "MEU PAPEL",
    role: "Ponta a ponta: descoberta, arquitetura, construção e implantação.",
    stats: [],
    tags: ["Next.js", "Fastify", "Prisma", "PostgreSQL", "Expo", "AWS · EKS"],
    cta: { label: "Ler o case do ERP", href: "/cases/erp" },
    figCaption: "Fig. 3 · Agenda do mês e o app da equipe",
    figNote: "dados de exemplo",
    before: "ANTES",
    notes: ["o combinado numa conversa", "contatos com o vendedor", "planilha_v7_FINAL2.xlsx", "histórico que sai com as pessoas"],
    windowTitle: "eventos · setembro 2026",
    screens: { month: "Agenda do mês com 67 shows por status", app: "App da equipe com a agenda do dia" },
  },
  others: {
    kicker: "OUTROS PROJETOS",
    title: "No meio do caminho.",
    items: [
      {
        kicker: "2025 · DADOS", title: "Plataforma de dados de clientes", figure: "data",
        body: "Os clientes de um grupo de bares viviam espalhados no PDV cashless. Unifiquei **17 milhões de eventos** num perfil por CPF, com **2,4 milhões de pessoas**, segmentos, campanhas e uma IA que responde perguntas sobre os dados.",
        stats: [], tags: ["ClickHouse", "TypeScript", "Next.js", "Supabase", "OpenAI"],
        link: { label: "Ler o case", href: "/cases/dados" },
      },
      {
        kicker: "2024 · FINANÇAS · DETERMINÍSTICO PRIMEIRO", title: "Conferência de notas fiscais", figure: "invoice",
        body: "**Mais de 3.000 notas por mês** eram conferidas à mão. Agora a conferência é automática e **determinística primeiro**: regras resolvem a maior parte, e OCR, modelo de visão e IA só entram quando elas falham. Menos custo, menos latência.",
        stats: [], tags: ["Python", "Tesseract", "Modelos de visão", "Fila", "AWS serverless", "MySQL"],
        link: { label: "Ler o case", href: "/cases/notas" },
      },
    ],
    social: {
      kicker: "ESPACES · CONTEÚDO",
      title: "Do zero a quase 20 mil no Instagram, em 1 ano.",
      body: "Em 1 ano, levei o Instagram da Espaces do zero a **quase 20 mil seguidores**. Eu ia até os lugares, narrava, gravava, editava e postava. Um dos vídeos passou de **1,9 milhão de visualizações**.",
      steps: ["ir ao lugar", "narrar", "gravar", "editar", "postar"],
      reels: [
        { label: "O vídeo viral · 1,9 milhão de visualizações", views: "1,9M+ views", photo: "/insta/viral-insights.jpg", ratio: "739 / 1200", hint: "" },
        { label: "O perfil · 19,8 mil seguidores", photo: "/insta/perfil.jpg", hint: "" },
      ],
    },
  },
  journey: {
    kicker: "TRAJETÓRIA", title: "Da planilha ao produto.",
    lanes: { edu: "formação", plat: "a plataforma", esp: "espaces" },
    graph: [
      { year: "2019", lane: "edu", tag: "Python" },
      { year: "2020", lane: "edu", tag: "CPA-20" },
      { year: "2021", lane: "plat", tag: "finanças" },
      { year: "2022", lane: "plat", tag: "automação" },
      { year: "2023", lane: "edu", tag: "formatura" },
      { year: "2023", lane: "plat", tag: "R$ 4M/mês" },
      { year: "2024", lane: "plat", tag: "PM" },
      { year: "2024", lane: "esp", tag: "cofundador" },
      { year: "2025", lane: "plat", tag: "produto" },
      { year: "2025", lane: "esp", tag: "dados e IA" },
      { year: "2026", lane: "plat", tag: "ERP" },
      { year: "2026", lane: "esp", tag: "infra" },
    ],
    items: [
      {
        year: "2019", title: "Engenharia de Produção", text: "No Mauá, um ano de algoritmos em Python me abriu os olhos para a programação.",
        detail: {
          body: "Entrei na Engenharia de Produção do Mauá. O primeiro ano de introdução a algoritmos foi um ano inteiro de **Python**, e foi isso que me abriu os olhos para a programação. No mesmo ano, fui do time que fundou a liga de mercado financeiro, onde fui diretor acadêmico e dava aulas de produtos financeiros.",
          points: ["Um ano de algoritmos em Python: a base de tudo o que veio depois", "Time fundador da liga de mercado financeiro", "Diretor acadêmico da liga, dando aulas de produtos financeiros"],
          tags: ["Python", "Algoritmos", "Finanças"],
        },
      },
      {
        year: "2020", title: "Mercado financeiro", text: "Python mais a fundo, primeiro contato com SQL e muito mercado financeiro.",
        detail: {
          body: "Um ano me preparando para trabalhar no mercado financeiro: **Python** mais a fundo, introdução ao **SQL** nas aulas de Sistemas de Informação e muito estudo de mercado.",
          points: ["4 cursos online de modelagem quantitativa, risco e decisão (Wharton)", "Operando como Institucional (Quantzed)", "Certificação CPA-20 (ANBIMA)", "Desafio Quantamental e Challenge IGC – M&A"],
          tags: ["Python", "SQL", "Finanças quantitativas"],
        },
      },
      {
        year: "2021", title: "Finanças, operações e inovação", text: "Entrei na maior plataforma de contratação de música ao vivo e passei a cuidar também de inovação.",
        detail: {
          body: "No fim de 2020, entrei na **maior plataforma de contratação de música ao vivo** para cuidar de finanças e operações. Rapidamente me destaquei montando os controles da área, e passei a responder também por **inovação**.",
          points: ["Montei os controles de finanças e operações, primeiro em planilha", "Passei a englobar a área de inovação"],
          tags: ["Finanças", "Operações", "Inovação"],
        },
      },
      {
        year: "2022", title: "Transformação do financeiro", text: "Saímos de processos manuais para automatizar boa parte do financeiro.",
        detail: {
          body: "O ano em que o financeiro deixou de depender de processos manuais. Automatizei boa parte do trabalho com **Python e SQL**, reduzi a dependência de tanta gente na equipe e aliviei os **gargalos** da operação.",
          points: ["Fechamentos que levavam **dias** passaram a levar **horas**", "Etapas manuais trocadas por scripts em Python e SQL", "Menos dependência de pessoas e gargalos aliviados"],
          stat: ["5→1", "pessoas na operação"],
          tags: ["Python", "SQL", "Automação"],
        },
      },
      {
        year: "2023", title: "A operação financeira", text: "Assumi a operação financeira da plataforma, me formei e entrei na Agenda Cultural.",
        detail: {
          body: "Assumi a responsabilidade pela operação financeira da plataforma: **100% do contas a pagar e do contas a receber** e o controle de **mais de R$ 4 milhões transacionados todo mês**. No mesmo ano, me formei. No fim do ano, me aproximei da **Agenda Cultural**, um portal para mostrar os shows feitos em mais de 200 bares e restaurantes pelo Brasil.",
          points: ["Responsável por 100% do contas a pagar e do contas a receber", "Controle de **mais de R$ 4 milhões** transacionados por mês na plataforma", "Formatura em Engenharia de Produção", "Agenda Cultural: os shows de **mais de 200 bares e restaurantes** pelo Brasil num portal"],
          stat: ["R$ 4M+", "transacionados por mês sob meu controle"],
          tags: ["Finanças", "Operações", "Produto"],
        },
      },
      {
        year: "2024", title: "Espaces e produto", text: "A Agenda Cultural vira a Espaces, e no fim do ano assumo produto na plataforma.",
        detail: {
          body: "A Agenda Cultural virou a **Espaces** e eu virei cofundador. No mesmo ano, automatizei a conferência de notas fiscais, **determinístico primeiro**. Depois da experiência com a Espaces, no fim do ano assumi também a área de **produto** da plataforma, atuando como product manager.",
          points: ["Cofundador da Espaces", "Conferência automática de **mais de 3.000 notas por mês**", "No fim do ano, product manager da plataforma"],
          stat: ["3.000+", "notas por mês conferidas sozinhas"],
          tags: ["Produto", "Python", "AWS"],
          links: [{ label: "Case da Espaces", href: "/cases/espaces" }, { label: "Case das notas fiscais", href: "/cases/notas" }],
        },
      },
      {
        year: "2025", title: "Dados, IA e produto", text: "Projetos de dados e IA mão na massa na Espaces, e produto perto do CEO na plataforma.",
        detail: {
          body: "Na Espaces, comecei projetos de **dados e IA** mais mão na massa, como a plataforma de dados de clientes, com **17 milhões de eventos** unificados em **2,4 milhões de pessoas**. Na plataforma, segui com produto: perto do CEO, definindo backlog, montando sprints e documentação.",
          points: ["Plataforma de dados de clientes com ClickHouse e IA para consultar e segmentar", "Produto na plataforma: backlog, sprints e documentação, perto do CEO"],
          stat: ["2,4M", "pessoas unificadas"],
          tags: ["ClickHouse", "OpenAI", "Produto"],
          links: [{ label: "Case dos dados", href: "/cases/dados" }],
        },
      },
      {
        year: "2026", title: "De volta ao código", text: "Mais mão na massa: o ERP sozinho e toda a infraestrutura da Espaces.",
        detail: {
          body: `Voltei mais para o código. Na plataforma, sigo responsável por produto e também pego tasks para fazer. Assumi sozinho o projeto do ERP, por falta de disponibilidade da equipe: hoje ele roda uma operação de **${R300} por ano**. Na Espaces, acelerei minha participação e virei dono de **toda a infraestrutura**.`,
          points: ["ERP assumido sozinho: **523 commits** em 7 meses", "Produto e tasks na plataforma", "Dono de toda a infraestrutura da Espaces"],
          stat: [R300, "por ano em operação no ERP"],
          tags: ["Next.js", "Fastify", "Prisma", "Kubernetes", "AWS"],
          links: [{ label: "Case do ERP", href: "/cases/erp" }],
        },
      },
    ],
  },
  how: {
    kicker: "COMO EU TRABALHO",
    title: "Negócio × Software × IA.",
    body: "Não sou só IA, nem só software. O que eu faço é juntar os dois com o negócio.",
    hint: "Passe o mouse ou toque nas regiões",
    circles: { b: "NEGÓCIO", s: "SOFTWARE", a: "IA" },
    regions: [
      { key: "bsa", label: "NEGÓCIO × SOFTWARE × IA", text: "Onde eu trabalho: entender o problema com quem vive ele, construir o sistema inteiro e usar IA onde ela realmente resolve. Até ter gente usando." },
      { key: "bs", label: "NEGÓCIO × SOFTWARE", text: "Sistemas que resolvem o problema, mas deixam na mesa o que a IA já faz bem." },
      { key: "ba", label: "NEGÓCIO × IA", text: "Boas ideias com IA que ficam no slide, porque ninguém constrói." },
      { key: "sa", label: "SOFTWARE × IA", text: "Tecnologia de ponta procurando um problema para resolver." },
      { key: "b", label: "SÓ NEGÓCIO", text: "Sabe exatamente o problema, mas depende de alguém para construir a solução." },
      { key: "s", label: "SÓ SOFTWARE", text: "Constrói bem, mas nem sempre o que mais importa para o negócio." },
      { key: "a", label: "SÓ IA", text: "Demos impressionantes que não chegam no dia a dia de ninguém." },
    ],
  },
  figures: {
    illustrative: "ilustrativo",
    enrichLabel: "O QUE A IA GERA PARA CADA LUGAR", enrichItems: ["Fotos selecionadas", "Descrição do lugar", "Links de cardápio e reserva"],
    builtLabel: "O QUE EU CONSTRUÍ", builtItems: ["App iOS e Android", "Site e páginas por bairro", "Painel para empresas", "APIs e infraestrutura na AWS"],
    stackLabel: "STACK", stack: ["React Native", "NestJS", "PostgreSQL", "pgvector", "Kubernetes", "AWS"],
  },
  foundations: {
    kicker: "FUNDAMENTOS", title: "De onde eu vim.", verify: "verificar ↗",
    degree: {
      years: "2019 — 2023",
      title: "Engenharia de Produção",
      school: "Instituto Mauá de Tecnologia",
      items: [
        { title: "Liga de Mercado Financeiro", text: "Time fundador · diretor acadêmico, dando aulas de produtos financeiros" },
      ],
    },
    certsLabel: "CERTIFICAÇÕES E CURSOS",
    certs: [
      { year: "2020", title: "4 cursos online de modelagem quantitativa, risco e decisão", issuer: "Wharton · University of Pennsylvania" },
      { year: "2020", title: "Operando como Institucional", issuer: "Quantzed", note: "trading, opções, carteira e estratégias quantitativas · nota 10" },
      { year: "2020", title: "CPA-20", issuer: "ANBIMA", note: "obtida no 2º ano da faculdade" },
    ],
  },
  life: {
    kicker: "ALÉM DO TRABALHO", title: "Fora da tela.", photoMissing: "foto em breve",
    items: [
      { title: "Tênis", photo: "/life/tenis.jpg", photoPos: "50% 22%", photoHint: "[sua foto jogando tênis]", text: "Joguei tênis competitivo e viajei para mais de 15 estados para disputar campeonatos brasileiros e sul-americanos." },
      { title: "Gastronomia", tag: "149+ avaliações na Espaces", photo: "/life/perfil-espaces.jpg", photoPos: "50% 0%", light: true, photoHint: "[um frame de um vídeo seu]", text: "Sair para comer sempre foi o meu programa. Indicar lugar para os amigos, também. A Espaces juntou isso com tecnologia." },
      { title: "Poker", photo: "/life/poker-campeao.jpg", framed: true, photoHint: "", text: "Estudei bastante e fiz alguns cursos quando era mais novo. Hoje jogo torneios online por diversão. Acho que muito do meu gosto por números e probabilidade veio daí." },
    ],
  },
  contact: {
    kicker: "CONTATO", title: "Tem um problema bagunçado?", text: "Estou aberto a novas oportunidades em IA aplicada, produto e engenharia. Me conta o que você está tentando resolver.",
    email: "fabio.gofferje@gmail.com", copy: "COPIAR", copied: "COPIADO", cv: "Currículo em breve", place: "São Paulo, Brasil",
  },
  footer: { made: "Feito à mão, com código." },
  espacesCase: {
    crumb: "01 · Espaces",
    next: { label: "Próximo case · ERP", href: "/cases/erp" },
    back: "Voltar aos projetos",
    kicker: "2023 — HOJE · COFUNDADOR · PRODUTO, ENGENHARIA, DADOS E INFRA",
    title: "Onde comer, pelo que seus amigos acharam.",
    lead: "Nota de desconhecido não ajuda a escolher onde jantar. A Espaces mostra onde as pessoas que você conhece comem de verdade e o que acharam, e deixa você pedir do seu jeito para um assistente com IA. Já passaram por ela **mais de 1 milhão de visitantes**, e **20 mil pessoas** criaram conta.",
    stats: [],
    galleryCaption: "Fig. 1 · O app, de ponta a ponta",
    gallery: [["feed", "Feed dos amigos"], ["rango", "Rango, assistente com IA"], ["avaliar", "Avaliação em quatro reações"], ["lugar", "Página do lugar"]],
    sections: [
      { title: "Um produto social", body: "O centro do app é o que a sua rede faz: cada avaliação traz foto, texto e uma de quatro reações. A página do lugar resume o que os seus amigos acharam antes da média geral." },
      { title: "Rango: IA dentro do produto", figure: "ai", body: "A pessoa pede do jeito dela, “um japonês bom e barato perto de mim”, e o Rango entende a intenção, não só as palavras. A busca é semântica e o que os amigos acharam pesa na ordem das sugestões." },
      { title: "Enriquecimento com IA", figure: "enrich", body: "Cada lugar ganha fotos selecionadas, descrição e links de cardápio e reserva, gerados por um pipeline com LLMs que roda todo dia em lote, com teto de custo e checagem dos links." },
      { title: "A plataforma", figure: "platform", body: "Apps iOS e Android, site, painel para empresas e APIs: serviços em NestJS rodando em Kubernetes na AWS, com PostgreSQL e pgvector. Eu desenho, construo e opero." },
    ],
    decisionsLabel: "DECISÕES QUE IMPORTARAM",
    decisions: [
      "Trocar a nota de 1 a 5 por quatro reações: não curti, ok, gostei e favorito. Mais rápido de avaliar e mais fácil de ler.",
      "Recomendar pelo que os seus amigos acharam, não pela média de desconhecidos.",
      "Enriquecer os lugares com IA em lote, com teto de custo por lugar, em vez de cadastrar tudo à mão.",
    ],
    lessonLabel: "O QUE EU FARIA DIFERENTE", lesson: "[Uma lição honesta sobre a Espaces]",
  },
  notasCase: {
    crumb: "03 · Notas fiscais",
    next: { label: "Próximo case · Dados de clientes", href: "/cases/dados" },
    back: "Voltar aos projetos",
    kicker: "2024 · FINANÇAS · DETERMINÍSTICO PRIMEIRO",
    title: "3.000 notas fiscais por mês. IA só onde precisa.",
    lead: "Todo mês, mais de **3.000 notas fiscais** de artistas chegavam para conferência manual. Construí o sistema que faz essa conferência sozinho, com um princípio: **determinístico primeiro**. Regex, listas e regras resolvem a maior parte; OCR, modelo de visão e IA só entram quando elas falham. Usar IA em tudo custaria muito mais e deixaria o retorno ao artista mais lento.",
    stats: [],
    specLabel: "O PROBLEMA EM NÚMEROS",
    spec: [["3.000+", "notas por mês"], ["5.000+", "prefeituras, cada uma com seu modelo"], ["3", "caminhos de leitura: texto, OCR e visão"], ["3", "campos conferidos com a base"]],
    sections: [
      { title: "Um trabalho que crescia com a operação", body: "Quanto mais shows, mais notas. A conferência era a mesma, repetida milhares de vezes por mês, e quem fazia não sobrava para mais nada.", items: ["Abrir cada PDF", "Achar CNPJ, valor e código de serviço", "Comparar com o que estava na base", "Avisar o artista quando algo não batia"] },
      { title: "Ler o que não é texto", figure: "invoice", body: "Nos casos comuns, ler o texto do PDF resolve. Mas parte das notas chegava escaneada, sem texto nenhum. Para essas, OCR com Tesseract; quando nem o OCR lia com confiança, um modelo de visão. Cada nota passa pelo caminho mais barato que funciona." },
      { title: "Determinístico primeiro, IA só onde precisa", body: "Cada prefeitura tem o seu modelo de nota: a posição e o nome de cada campo mudam de um município para outro, e às vezes até pelo regime tributário da empresa. Mandar toda nota para um modelo de IA resolveria, mas com um custo enorme e mais latência. Por isso a extração tenta primeiro o caminho determinístico, e só o que as regras não resolvem vai para a IA.", items: ["Regex para encontrar os CNPJs", "Lista de códigos de serviço para identificar o código", "Listas de rótulos para achar o campo de valor", "Modelo de IA como fallback, só para classificar o que sobrou"] },
      { title: "Conferir o que importa", body: "A nota não precisa ser entendida inteira. Precisa bater em três campos com o que era esperado na base: CNPJ, valor e código de serviço. Quando algo diverge, o artista sabe exatamente o que corrigir." },
      { title: "Rápido e em fila", body: "O artista precisava de retorno rápido, e no fim do mês o volume chega de uma vez. As notas entram numa fila e são processadas por funções serverless na AWS, em Python, lendo e gravando na base MySQL da empresa." },
    ],
    decisionsLabel: "DECISÕES QUE IMPORTARAM",
    decisions: [
      "IA só onde o determinístico não resolve: na leitura (texto, depois OCR, depois modelo de visão) e na extração (regex e listas, depois IA). Custo e latência ficam baixos.",
      "Conferir os três campos que decidem a nota, em vez de tentar entender a nota inteira.",
      "Fila e serverless para absorver o pico de fim de mês sem servidor parado o resto do tempo.",
    ],
    lessonLabel: "O QUE EU FARIA DIFERENTE", lesson: "[Uma lição honesta sobre o projeto]",
  },
  cdpCase: {
    crumb: "04 · Dados de clientes",
    next: { label: "Próximo case · Espaces", href: "/cases/espaces" },
    back: "Voltar aos projetos",
    kicker: "2025 · DADOS · DETERMINÍSTICO + IA",
    title: "2,4 milhões de pessoas, um perfil para cada uma.",
    lead: "Os dados dos clientes de um grupo de bares e restaurantes viviam espalhados no PDV cashless: check-in de um lado, pagamento de outro, itens vendidos de outro. Construí a plataforma que junta tudo num perfil por CPF, com **2,4 milhões de pessoas**, e deixa o marketing segmentar, perguntar aos dados com IA e disparar campanhas.",
    stats: [],
    specLabel: "A GRANDEZA DOS DADOS",
    spec: [["17M", "eventos de check-in, compra e itens"], ["2,4M", "pessoas, uma por CPF"], ["10M", "linhas de pessoa × produto"], ["3,4M", "linhas de pessoa × casa"], ["11", "casas, cada uma vendo só o que é dela"]],
    sections: [
      { title: "Uma pessoa, três registros", figure: "identity", body: "O PDV entrega a mesma visita em três pedaços: o check-in que abre a comanda, o comprador que paga e os itens vendidos. O CPF é o único dado consistente, porque o PDV exige CPF para abrir comanda. A partir dele, as regras juntam campo a campo, com prioridade por fonte; um dado preenchido nunca é apagado por um vazio, e cada campo guarda de onde veio e quando mudou." },
      { title: "Limpar o que a API entrega", body: "Metade do trabalho foi descobrir os jeitos que a API erra. Cada um virou uma regra determinística, testada contra os eventos reais.", items: ["Hora em UTC com um fuso -03:00 falso", "O mesmo UUID reaproveitado em dias diferentes", "Dia operacional das 3h às 3h, não da meia-noite", "CPF com * no fim e telefone em notação científica", "Nomes com dígitos, caixa alta e acento perdido"] },
      { title: "ClickHouse para responder rápido", body: "Começou em Postgres, com as métricas guardadas em JSON. Quando o volume cresceu, o analítico foi para o ClickHouse: eventos particionados por mês, pessoas com versões substituídas a cada carga e materialized views que já deixam pronto o que o painel pergunta. A carga roda de hora em hora e pode rodar de novo sem duplicar nada.", items: ["Consultas de produto cerca de 120x mais rápidas que o JSON", "Métricas por pessoa × casa batendo 100% com os eventos brutos", "Carga idempotente: cada evento tem um id de origem"] },
      { title: "Perguntar aos dados com IA", figure: "analyst", body: "O marketing pergunta em português e a IA escreve o SQL. Antes de rodar, uma trava confere: só leitura, filtro pelas casas que a pessoa pode ver e nenhum dado de documento. Para montar segmento por chat, a IA busca produtos e categorias com ferramentas, em vez de receber o catálogo inteiro no prompt." },
      { title: "Do segmento à campanha", body: "Segmentos são regras guardadas em JSON e avaliadas no ClickHouse com SQL parametrizado. Dali saem campanhas por e-mail, com rastreio de clique, e por WhatsApp, com templates aprovados na Meta. O disparo saiu da Vercel e foi para o worker do ETL quando os timeouts começaram a matar envios no meio." },
    ],
    decisionsLabel: "DECISÕES QUE IMPORTARAM",
    decisions: [
      "CPF como chave única e determinística: o PDV exige CPF para abrir comanda, então dá para unir sem fuzzy match.",
      "Idempotência desde a primeira carga: rodar de novo nunca duplica, porque cada evento tem um id de origem e as tabelas substituem versões.",
      "Métricas por pessoa × casa, não globais: as 35 visitas de um cliente no grupo viram 29 + 3 + 3, e cada casa vê só o que é dela.",
    ],
    lessonLabel: "O QUE EU FARIA DIFERENTE",
    lesson: "[Rascunho, confira] Normalizei nomes e telefones depois que os dados já estavam entrando. A regra nova vale para as cargas futuras, mas o que já estava gravado continua sujo. Hoje eu limparia tudo na entrada desde o primeiro dia.",
  },
  erpCase: {
    crumb: "02 · ERP",
    next: { label: "Próximo case · Notas fiscais", href: "/cases/notas" },
    back: "Voltar aos projetos",
    kicker: "2026 · SISTEMAS · CONSTRUÍDO COM IA",
    title: `Um ERP para uma operação de ${R300} por ano.`,
    lead: "Numa produtora de shows, o combinado morava numa conversa, os contatos ficavam com o vendedor e cada pessoa conhecia um pedaço da operação. Quando alguém saía, o histórico ia junto. Construí do zero o sistema que hoje roda essa operação, com **mais de 100 pessoas** usando todos os dias.",
    stats: [],
    specLabel: "EM NÚMEROS DE ENGENHARIA",
    spec: [["7 meses", "do primeiro commit ao sistema rodando"], ["523", "commits, 94% meus"], ["107 mil", "linhas de TypeScript"], ["52 · 270", "tabelas · endpoints"]],
    screensCaption: "Fig. 1 · O sistema, módulo a módulo",
    screensNote: "telas de apresentação, com dado de exemplo",
    screens: [["eventos-mes", "Operacional · agenda do mês"], ["clientes", "Comercial · histórico da relação"], ["contratos", "Jurídico · contrato gerado do evento"], ["receber", "Financeiro · contas a receber e repasse"]],
    sections: [
      { title: "A operação morava nas pessoas", body: "Planilha, conversa e agenda pessoal funcionam enquanto as mesmas pessoas continuam ali. O objetivo não era trocar a planilha por telas: era fazer contatos, negociações e histórico virarem ativo da empresa.", items: ["O combinado morava numa troca de mensagens", "Os contatos ficavam no WhatsApp de quem vendia", "Cada pessoa conhecia um pedaço da operação", "Quando alguém saía, o contexto ia junto"] },
      { title: "Seis módulos, um fluxo só", figure: "flow", body: "Comercial, jurídico, fiscal, operacional e financeiro são o mesmo evento passando de mão em mão. O contrato nasce do evento, o pedido de venda nasce do contrato e o repasse nasce da regra de pagamento. Ninguém redigita nada." },
      { title: "Regras que não dependem de memória", body: "A governança está no código, não no hábito de quem usa.", items: ["Toda escrita gera log de alteração; toda mudança de status gera histórico", "Status e aprovação são campos separados: cadastro feito por vendedor nasce pendente até a qualidade aprovar", "10 perfis de acesso, verificados em toda rota de escrita", "Toda entrada validada com Zod; CPF e CNPJ únicos"] },
      { title: "Simular antes de ligar", body: "Uma regra nova cancelaria automaticamente reservas sem contrato a 72 horas do show. Antes de ligar, rodei a regra contra os dados reais de produção: a primeira versão derrubaria shows ainda em negociação ativa. Ajustamos o critério com a operação, e a regra só liga depois de simulada." },
      { title: "Construído com IA", body: "Escrevi 94% dos 523 commits em 7 meses, com IA como par de programação. As regras do projeto vivem num documento que a IA lê antes de qualquer mudança. A IA escreve código e SQL; o que toca o banco de produção, quem roda sou eu." },
    ],
    stepsLabel: "DA IMPLANTAÇÃO À ROTINA",
    steps: [
      ["Diagnóstico", "Entender como a operação funcionava: quem vende, quem opera, onde trava e o que vivia em planilha."],
      ["Personalização", "Regras de comissão, modelos de contrato, tipos de evento e permissão por time desenhados para aquela operação."],
      ["Implantação", "Cadastros, histórico e agenda migrados por etapa, com a equipe treinada no que usa, sem parar o escritório."],
      ["Operação", "Acompanhar até o primeiro mês inteiro fechar dentro do sistema e ajustar o que a rotina mostrou."],
    ],
    decisionsLabel: "DECISÕES QUE IMPORTARAM",
    decisions: [
      "Um evento como espinha dorsal: contrato, pedido de venda e conta a receber nascem dele, em vez de cada área ter o seu cadastro.",
      "Separar status de aprovação, para a operação andar sem pular a governança.",
      "O sistema controla o dinheiro, mas não movimenta: contas a receber, regras de pagamento e fechamento, sem acesso à conta bancária.",
    ],
    lessonLabel: "O QUE EU FARIA DIFERENTE",
    lesson: "[Rascunho, confira] Construindo rápido com IA, deixei a checagem de tipos e os testes fora do CI. Uma rota quebrada passou meses sem ninguém ver. Hoje eu colocaria type-check e testes no pipeline no primeiro dia.",
  },
};
